# configuration file for ${project.name} v${project.version}

# Localization language
language: en-US


# enabled worlds list
# if this list is empty, all worlds will be added to the enabled worlds list
# otherwise, only listed worlds will be added to the enabled worlds list
# Note: explicitly declare empty list for testing
enabled-worlds: []
#  - enabled_world1
#  - enabled_world2


# disabled worlds list
# these worlds will be removed from the enabled worlds list created by the previous setting
disabled-worlds:
  - disabled_world1
  - disabled_world2

# delay chest deployment (in ticks)
chest-deployment-delay: 2

# log player's inventory on death
log-inventory-on-death: false

# Use sound effects
sound-effects: true

# Time in minutes before death chests expire. Set to negative integer to disable chest expiration.
expire-time: 60

# Protect chests from other players
chest-protection: true

# Time in minutes chests will be protected from other players, if enabled.
# Set to negative integer to match chest expire time and suppress relevant messages.
chest-protection-time: -1

# Allow player's killer to access death chest
killer-looting: false

# Require players to have a chest in their inventory
require-chest: false

# remove required chests from inventory on use
consume-required-chest: true

# prevent placing items in death chests
prevent-item-placement: true

# deploy chests for players in creative mode
creative-deploy: false

# allow access to chests for players in creative mode
creative-access: false

# Distance from death location to search for a valid chest location
# NOTE: This checks exponentially more locations for each increase in distance
# For this reason, it is not recommended to set this value too high.
search-distance: 10

# Place chests above the void when players die below world minimum height
place-above-void: true

# Allow quick-looting of chests with sneak-punch
quick-loot: true

# number of DeathChests shown per page in list command
list-page-size-player: 5
list-page-size-console: 10

# Place sign on death chests
chest-signs: true

# Custom sign text
# Variable substitutions:
# %PLAYER%  Player's name
# %WORLD%   World name
# %DATE%    Death date
SIGN_TEXT:
  - '&lR.I.P.&r'
  - '%PLAYER%'
  - ''
  - 'D: %DATE%'

# Date format documentation:
# https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
DATE_FORMAT: "MMM d, yyyy"

# Ignore protection plugin permissions on death chest placement or access
protection-plugins:
  WorldGuard:
    ignore-on-place: false
    ignore-on-access: true

  Towny:
    ignore-on-place: false
    ignore-on-access: true

  GriefPrevention:
    ignore-on-place: false
    ignore-on-access: true

  RoadBlock:
    ignore-on-place: false
    ignore-on-access: true

  PreciousStones:
    ignore-on-place: false
    ignore-on-access: true


# List of block materials that can be replaced by a chest
replaceable-blocks:
  - AIR
  - CAVE_AIR
  - GRASS
  - TALL_GRASS
  - SNOW
  - VINE
  - LILY_PAD
  - WATER
  - LAVA
