name: ${project.name}
main: com.winterhavenmc.deathchest.PluginMain
author: ${project.author}
version: ${project.version}
api-version: 1.18
softdepend: [ GriefPrevention, Iris, Lands, Multiverse-Core, My_Worlds, PreciousStones, RoadBlock, Towny, WorldGuard ]

commands:
   deathchest:
      aliases: sdc
      description: "This is the DeathChest command."
      permission-message: "You don't have required permission <permission>."
      usage: "/<command> [command]"

permissions:
  deathchest.chest:
    description: "Allow the creation of a death chest."
    default: true

  deathchest.loot:
    description: "Allow player to quick-loot death chests by sneak-punching."
    default: true

  deathchest.loot.killer:
    description: "Allow player to loot death chests of players they have killed."
    default: true

  deathchest.loot.other:
    description: "Allow player to quick-loot other player's chests."
    default: op

  deathchest.freechest:
    description: "Override require chest in inventory configuration."
    default: op
    
  deathchest.creative-access:
    description: "Override restriction on opening death chests in creative mode."
    default: op
    
  deathchest.allow-place:
    description: "Override restriction on placing items in death chests."
    default: op

  deathchest.doublechest:
    description: "Allow placement of double chests if necessary."
    default: true

  deathchest.help:
    description: "Allow viewing plugin help."
    default: true

  deathchest.list:
    description: "Allow viewing list of deathchests."
    default: op

  deathchest.list.other:
    description: "Allow viewing a list of other player's deathchests."
    default: op

  deathchest.reload:
    description: "Allow reloading the config file."
    default: op

  deathchest.status:
    description: "Allow viewing deathchest status."
    default: op

  deathchest.player:
    description: "Default permissions."
    default: true
    children:
      deathchest.chest: true
      deathchest.loot: true
      deathchest.doublechest: true

  deathchest.admin:
    description: "Give access to DeathChest admin commands."
    default: op
    children:
      deathchest.freechest: true
      deathchest.loot.other: true
      deathchest.creative-access: true
      deathchest.allow-place: true
      deathchest.reload: true
      deathchest.status: true
      deathchest.list: true
      deathchest.list.other: true
